version: "3.9"

services:
  SqlServer:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "9433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SqlServerPassword}
    volumes:
      - MA_SqlData:/var/opt/mssql
    restart: unless-stopped

  # Seq:
  #   image:  datalust/seq:latest
  #   ports:
  #     - "5345:80"
  #   environment:
  #     ACCEPT_EULA: "Y"
  #   volumes:
  #     - MA_SeqData:/data
  #   restart: unless-stopped

  # Redis:
  #   image: redis:latest
  #   ports:
  #     - "16379:6379"
  #   volumes:
  #     - MA_RedisData:/data
  #   restart: unless-stopped

  # rabbitmq:
  #   image: rabbitmq:management
  #   ports:
  #     - "5672:5672"   # RabbitMQ main port
  #     - "15672:15672" # RabbitMQ management plugin port
  #   environment:
  #     RABBITMQ_DEFAULT_USER: user
  #     RABBITMQ_DEFAULT_PASS: password
  #   volumes:
  #     - MA_RabbitmqData:/var/lib/rabbitmq
  #   restart: unless-stopped

volumes:
  MA_SqlData:
    external: true

  # MA_RedisData:
  #   external: true

  # MA_SeqData:
  #   external: true

  # MA_RabbitmqData:
  #   external: true
